<a href="https://colab.research.google.com/github/nsingh216/edu/blob/master/tf0/Exercise_Tensorflow_Tensors.ipynb" target="_blank"><img src="https://colab.research.google.com/assets/colab-badge.svg"/></a>

## Import the __`tensorflow`__ package

In [1]:
import tensorflow as tf
tf.random.set_seed(0);

## Create a vector of ten zeros

In [2]:
vec1 = tf.zeros(10)

In [3]:
vec1.numpy()

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

## Create a vector of size ten with nine zeros and a 1 in the fifth position

In [4]:
vec2 = tf.eye(10)[4]
vec2.numpy()

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.], dtype=float32)

## Create a vector with values ranging from 10 to 49

In [5]:
# shape and data type not specified ?
vec3 = tf.random.uniform(shape=[10], minval=10, maxval=49)

In [6]:
vec3

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([21.387032, 18.056091, 30.88024 , 31.889042, 26.250305, 41.50529 ,
       29.235779, 48.92704 , 37.17267 , 14.88957 ], dtype=float32)>

## Reverse the previous vector

In [7]:
# must specific which axis to reverse
vec3_rev = tf.reverse(vec3, [0])
vec3_rev.numpy()

array([14.88957 , 37.17267 , 48.92704 , 29.235779, 41.50529 , 26.250305,
       31.889042, 30.88024 , 18.056091, 21.387032], dtype=float32)

## Create a 3x3 matrix with values ranging from 0 to 8

In [8]:
vec4 = tf.random.uniform(shape=[3, 3], minval=0, maxval=9, dtype=tf.int32)
vec4

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[7, 3, 3],
       [1, 1, 8],
       [2, 5, 4]], dtype=int32)>

## Find the indices of the non-zero elements of the following array:

In [9]:
v = tf.constant([1, 2, 0, 0, 4, 0]) # Given
v

<tf.Tensor: shape=(6,), dtype=int32, numpy=array([1, 2, 0, 0, 4, 0], dtype=int32)>

In [10]:
# better to reshape to the desired shape instead of squeeze, especially for development
v_ind = tf.squeeze(tf.where(v != 0))
v_ind

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([0, 1, 4])>

## Create a 5x5 identity matrix

In [11]:
vec5 = tf.eye(5)
vec5

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

## Create a 3x3x3 array with random values

In [12]:
# maxval is required for dtype int, defaults to 1 for float
vec6 = tf.random.uniform(shape=[3, 3, 3], 
                         maxval = 100, 
                         dtype=tf.int32)
vec6

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[84, 47, 34],
        [79,  6, 35],
        [44, 18, 19]],

       [[66,  4, 15],
        [87, 90, 15],
        [21, 32, 36]],

       [[46, 90, 25],
        [47, 62, 25],
        [66, 85, 71]]], dtype=int32)>

## Find the minimum and maximum values generated in the previous step

In [13]:
print(f"min: {tf.reduce_min(vec6)}, max: {tf.reduce_max(vec6)}") 

min: 4, max: 90


## Create a vector with 30 random values and find its mean

In [14]:
vec7 = tf.random.uniform(
    shape=[30]
)

print(vec7.numpy())

the_mean = tf.math.reduce_mean(vec7)
print(the_mean)

[0.17513537 0.3179742  0.8555474  0.41725898 0.23591995 0.22561431
 0.59902835 0.8288827  0.59770846 0.48930836 0.11657119 0.40833473
 0.12059581 0.93723166 0.23596966 0.80262804 0.09374154 0.07246888
 0.08392537 0.20400608 0.6407254  0.7407241  0.69874144 0.63659525
 0.74655735 0.6835319  0.6907762  0.7909107  0.8290696  0.5960953 ]
tf.Tensor(0.49571928, shape=(), dtype=float32)


## Create a 5x5 2d array with 1s around the edges and 0s in the middle

In [15]:
# start by filling in all zeros
vec8 = tf.Variable(tf.zeros(shape=(5,5)), dtype=tf.float32)

# then add the ones around the edge
ones = tf.ones(shape=(5))
vec8[0,:].assign(ones)
vec8[-1,:].assign(ones)
vec8[:,0].assign(ones)
vec8[:,-1].assign(ones)

# x = tf.gather(vec8, [0,-1]).assign(ones)


<tf.Variable 'UnreadVariable' shape=(5, 5) dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

## Try to predict the output of each of the following cells before running them

In [16]:
0 * float('nan') # nan

nan

In [17]:
float('nan') == float('nan') # false

False

In [18]:
float('inf') > float('nan') # false

False

In [19]:
float('nan')

nan

In [20]:
float('nan') - float('nan') # not 0 | it's still nan

nan

In [21]:
0.3 == 3 * 0.1 # false

False

In [22]:
tf.constant([0]) // tf.constant([0]) # can you divide by 0 in TF | no, div by 0 error

InvalidArgumentError: ignored

In [23]:
tf.constant([0.0]) // tf.constant([0.0]) # inf | nan

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([nan], dtype=float32)>

In [25]:
nan_scalar = tf.constant([float('nan')]) 

tf.math.is_nan(nan_scalar) # true

<tf.Tensor: shape=(1,), dtype=bool, numpy=array([ True])>

In [26]:
tf.constant([0.0]) / tf.constant([0.0]) # nan, same as above

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([nan], dtype=float32)>

## Find the integer part of the following array using four different methods:

In [27]:
a = tf.random.normal((10,), dtype = tf.float32)
a

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([ 1.61399   ,  2.4495301 , -1.1530102 , -0.33435348, -0.48866138,
       -1.3499267 ,  0.40876192, -0.755513  ,  1.2192806 ,  1.2861389 ],
      dtype=float32)>

In [28]:
a_int = tf.cast(a, tf.int8)
a_int

<tf.Tensor: shape=(10,), dtype=int8, numpy=array([ 1,  2, -1,  0,  0, -1,  0,  0,  1,  1], dtype=int8)>

In [29]:
# floor

In [30]:
# ceiling

In [31]:
# truncate

## Create a vector of 10 values from 0 to 1, both included

In [32]:
# evenly distributed
vec10 = tf.linspace(start = 0, stop=1, num=10)
vec10

<tf.Tensor: shape=(10,), dtype=float64, numpy=
array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])>

## Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [33]:
vec11 =  tf.random.uniform(shape=[10], minval =1e-6, maxval=1)
vec11

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([0.39729905, 0.6661668 , 0.15123095, 0.9818742 , 0.7510545 ,
       0.6180992 , 0.74969757, 0.8060493 , 0.22680658, 0.06904433],
      dtype=float32)>

## Subtract the mean of each row of the following matrix

In [34]:
m = tf.random.uniform((3, 3))
m

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.05311072, 0.18923342, 0.97226834],
       [0.01325536, 0.16124213, 0.59450936],
       [0.9958024 , 0.61298347, 0.1633718 ]], dtype=float32)>

In [35]:
row_means = tf.reshape(tf.math.reduce_mean(m, axis=1), shape=[3, 1])
row_means

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[0.40487084],
       [0.25633562],
       [0.5907192 ]], dtype=float32)>

In [36]:
m_final = m -row_means
m_final.numpy()

array([[-0.35176012, -0.21563742,  0.5673975 ],
       [-0.24308026, -0.09509349,  0.33817375],
       [ 0.40508318,  0.02226424, -0.42734742]], dtype=float32)

In [37]:
row_means = tf.math.reduce_mean(m, axis=1, keepdims=True) # keepdims is doing same thing as additional reshape
row_means

<tf.Tensor: shape=(3, 1), dtype=float32, numpy=
array([[0.40487084],
       [0.25633562],
       [0.5907192 ]], dtype=float32)>

## Add 1,000,000 numbers together using __`tensorflow`__ vectorized operations

In [38]:
v = tf.random.uniform(shape =[1000000, 1])
print(tf.math.reduce_mean(v))


tf.Tensor(0.5002016, shape=(), dtype=float32)


## Create a 4x4 array of the first 16 powers of 3

In [39]:
lastOne = tf.reshape(tf.Variable(initial_value=3**tf.range(0, 16)), shape=[4,4])
lastOne

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[       1,        3,        9,       27],
       [      81,      243,      729,     2187],
       [    6561,    19683,    59049,   177147],
       [  531441,  1594323,  4782969, 14348907]], dtype=int32)>

Copyright 2021 CounterFactual.AI LLC. Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.